@mklink    "%HOME%\.aliases"       "%~dp0src\.aliases"
@mklink    "%HOME%\.bash_profile"  "%~dp0src\.bash_profile"
@mklink    "%HOME%\.bashrc"        "%~dp0src\.bashrc"
@mklink    "%HOME%\.editorconfig2" "%~dp0src\.editorconfig"
@mklink    "%HOME%\.environment"   "%~dp0src\.environment"
@mklink    "%HOME%\.gitconfig"     "%~dp0src\.gitconfig"
@mklink    "%HOME%\.minttyrc"      "%~dp0src\.minttyrc"
@mklink    "%HOME%\.vimrc"         "%~dp0src\.vimrc"
