#!/usr/bin/env zsh

local _count
_count=$(find . -maxdepth 1 -type d \( -name .git -o -name node_modules \) -prune -o -maxdepth 2 -print 2>/dev/null | wc -l)

if (( _count < LINES )); then
    BUFFER=" exa --long --tree --classify --color=always --all --level 2 --ignore-glob '.git|node_modules' --git-ignore --group --header --time-style long-iso --git"
else
    BUFFER=" exa --long --classify --color=always --all --group --header --time-style long-iso --git"
fi

zle accept-line
