set -g prefix C-a

unbind C-b
bind -n C-b send-prefix

set-option -g status-position top

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# copying
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# catppuccin mocha style
set -g status-justify "left"
set -g status 2
set -g status-format[1] ''
set -g status-left "  "
set -g status-right "  "
set -g status-style "bg=default"
set -g message-style "fg=#cdd6f4,bg=#313244"
set -g message-command-style "fg=#cdd6f4,bg=#313244"
set -g pane-active-border-style "fg=#585b70"
set -g pane-border-style "fg=#585b70"
set -g status-right "  "
set -g status-left "  "
setw -g window-status-activity-style "none"
setw -g window-status-separator "  "
setw -g window-status-style "fg=#6c7086"
setw -g window-status-current-style "fg=#1e1e2e,bold"
set -g status-left " "
set -g status-right "  "
setw -g window-status-format "#[fg=#45475a,bg=default]#[fg=#cdd6f4,bg=#45475a]#I #[default,bg=#313244] #W #[fg=#313244,bg=default]"
setw -g window-status-current-format "#[fg=#cba6f7,bg=default]#[fg=#1e1e2e,bg=#cba6f7,bold]#I #[default,bg=#cba6f7] #W #[fg=#cba6f7,bg=default]"

set -g @thumbs-regexp-1 '[.\w\-@]+\.[.\w\-@]{2,5}'
set -g @thumbs-command 'echo -n {} | pbcopy'
set -g @thumbs-upcase-command 'echo -n {} | pbcopy'

# Tmux Plugin Manager
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'knakayama/tmux-man'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @man-size 15

run '~/.tmux/plugins/tpm/tpm'

# shift arrow to switch windows
bind -T root -n S-Left  previous-window
bind -T root -n S-Right next-window

# popup
bind-key "p" popup -E -d '#{pane_current_path}' -w 80% -h 80%

# mouse
set -g mouse on
