name: Add to project

on:
  issues:
    types: [opened, reopened, transferred]
  pull_request_target:
    types: [opened, reopened]

permissions: {}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/m5d215/projects/1
          github-token: ${{ secrets.PROJECT_PAT }}
